# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cnappgoat < Formula
  desc "CNAPPgoat is an open source project designed to modularly provision vulnerable-by-design components in cloud environments"
  homepage "https://github.com/ermetic-research/cnappgoat"
  version "0.2.0-beta"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ermetic-research/cnappgoat/releases/download/v0.2.0-beta/cnappgoat_0.2.0-beta_macOS-ARM64.tar.gz"
      sha256 "b9d83ee42d86b30c5e85ccccef957b3b84b7fae326e6180895757afddd243cff"

      def install
        bin.install "cnappgoat"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ermetic-research/cnappgoat/releases/download/v0.2.0-beta/cnappgoat_0.2.0-beta_macOS-64bit.tar.gz"
      sha256 "2da4666da38bf7f4f1e1d4bda1b2683f77a25e74a9c1fe36501d8359cd1baad7"

      def install
        bin.install "cnappgoat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ermetic-research/cnappgoat/releases/download/v0.2.0-beta/cnappgoat_0.2.0-beta_Linux-ARM64.tar.gz"
      sha256 "79192b03d6abc888aa1c2573a31a7de1d30adb8ecc309c31434292074bac832d"

      def install
        bin.install "cnappgoat"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ermetic-research/cnappgoat/releases/download/v0.2.0-beta/cnappgoat_0.2.0-beta_Linux-64bit.tar.gz"
      sha256 "bdac163179611a290fff37163a597099d80d3591a3b147f9779a544905a1a440"

      def install
        bin.install "cnappgoat"
      end
    end
  end

  test do
    system "#{bin}/cnappgoat", "--version"
  end
end
