# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Testr < Formula
  desc "CNAPPgoat is an open source project designed to modularly provision vulnerable-by-design components in cloud environments"
  homepage "https://github.com/ermetic-research/cnappgoat"
  version "0.1.0-beta"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ermetic-research/cnappgoat/releases/download/v0.1.0-beta/cnappgoat_0.1.0-beta_macOS-ARM64.tar.gz"
      sha256 "3747dd3da9825fbe2f666d0adfeb37e25b01cdacb5d637e2253caa70554b9901"

      def install
        bin.install "cnappgoat"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ermetic-research/cnappgoat/releases/download/v0.1.0-beta/cnappgoat_0.1.0-beta_macOS-64bit.tar.gz"
      sha256 "7cdd478a04a47e39006ab1daf054e9d3ba54e334849b57adaaf12823a1587d4a"

      def install
        bin.install "cnappgoat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ermetic-research/cnappgoat/releases/download/v0.1.0-beta/cnappgoat_0.1.0-beta_Linux-ARM64.tar.gz"
      sha256 "defa8a4d41b2db355557221c9ae47508084425166e2641754f8d9201d17e35ca"

      def install
        bin.install "cnappgoat"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ermetic-research/cnappgoat/releases/download/v0.1.0-beta/cnappgoat_0.1.0-beta_Linux-64bit.tar.gz"
      sha256 "9dcb31d039cfec4024f6307c08d1a9010a8eeb02b880709860465ac38cf93162"

      def install
        bin.install "cnappgoat"
      end
    end
  end

  test do
    system "#{bin}/cnappgoat", "--version"
  end
end
